name: ISOcentVIP
main: cc.isotopestudio.ISOcentVIP.ISOcentVIP

author: Mars
description: ISOcentVIP
website: http://isotopestudio.cc
version: 1.0.5
depend: [PlayerPoints]
softdepend: [PlaceholderAPI]
commands:
  vipadmin:
    description: ISOcentVIP Admin command
    usage: /<command> - Get Information
    aliases: vipa
  vip:
    description: ISOcentVIP command
    usage: /<command> - Get Information